CLASS zcl_gfo_trip DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    TYPES:
      tt_trip TYPE STANDARD TABLE OF REF TO zcl_gfo_trip WITH EMPTY KEY .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_GFO_TRIP IMPLEMENTATION.
ENDCLASS.
